apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - namespace-prod.yaml
  - hpa.yaml
  - dragonfly.yaml

patches:
  - path: deployment.yaml