apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: course-app-production
  namespace: flux-system
spec:
  interval: 1m              
  path: ./overlays/production 
  sourceRef:
    kind: GitRepository
    name: flux-system       
  targetNamespace: production 